### ISSUE TITLE
leave radio when dead

### ISSUE THREAD

**Issue by Andyauk** [trclassic92/qb-radio-v2#1]
you don't seem to leave the channel when down, as ems and police.

**Comment by trclassic92** [comment]
> you don't seem to leave the channel when down, as ems and police.

This is forked from qb-radio so if this is a issue with this radio then its a issue with the main radio.

But I will update it to fix it

**Comment by Andyauk** [comment]
> > you don't seem to leave the channel when down, as ems and police.
> 
> This is forked from qb-radio so if this is a issue with this radio then its a issue with the main radio.
> 
> But I will update it to fix it

ah ok, thanks

**Comment by trclassic92** [comment]
> > > you don't seem to leave the channel when down, as ems and police.
> > 
> > 
> > This is forked from qb-radio so if this is a issue with this radio then its a issue with the main radio.
> > But I will update it to fix it
> 
> ah ok, thanks

I think by default if you are dead while on the radio you can no longer use it.... but you can still hear people.
