### ISSUE TITLE
Disables all controls

### ISSUE THREAD

**Issue by JonasDev17** [trclassic92/qb-radio-v2#4]
On a clean install of QBCore when using the radio it shows up but then you can't do anything as it disables all controls / you can't do anything anymore.

**Comment by trclassic92** [comment]
> On a clean install of QBCore when using the radio it shows up but then you can't do anything as it disables all controls / you can't do anything anymore.

This still an issue

**Comment by JonasDev17** [comment]
> > On a clean install of QBCore when using the radio it shows up but then you can't do anything as it disables all controls / you can't do anything anymore.
> 
> This still an issue

No idea, I no longer run a server 😅
